<?php

namespace Teneleven\Bundle\FormHandlerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubmissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubmissionRepository extends EntityRepository
{
}
